= Container Diagram
Marc Guillen <mguillen@pictet.com>
v1.0, 2022-05-01

The Container Diagram shows the high-level shape of the software architecture and how responsibilities are distributed across it. It also shows the major technology choices and how the containers communicate with one another. It's a simple, high-level technology focussed diagram that is useful for software developers and support/operations staff alike.

[.helptext]
****
[NOTE]
====
* *Scope:* A single software system.
* *Primary elements:* Containers within the software system in scope.
* *Supporting elements:* People and software systems directly connected to the containers.
* *Intended audience:* Technical people inside and outside of the software development team; including software architects, developers and operations/support staff.
* *Description:* Once you understand how your system fits in to the overall IT environment (see Context Diagram), a really useful next step is to zoom-in to the system boundary with a Container diagram. A "container" (do not confuse with Docker) is something like a server-side web application, single-page application, desktop application, mobile app, database schema, file system, etc. Essentially, a container is a separately runnable/deployable unit (e.g. a separate process space) that executes code or stores data. Note that this diagram says nothing about deployment scenarios, clustering, replication, failover, etc.
====
****

*Date:* YYYY-MM-DD

*Status:* Proposed | Accepted | Deprecated

[.helptext]
****
[NOTE]
====
The goal is to communicate the visual representation of your system with the https://c4model.com[C4 Model] convention. 

To produce the schema you have basically two possibilities:

. *draw and export* - Draw and export as an image from https://app.diagrams.net/[diagram.net]. Diagram has C4 shapes by default.
. *model and generate* - Model with https://structurizr.com/dsl[structurizr DSL], the schema will be generated automatically with https://kroki.io/[kroki].
====
****

[structurizr,main,svg,view-key=Containers]
----
include::ROOT:partial$/workspace.dsl[]
----