= System Context Diagram
Marc Guillen <mguillen@pictet.com>
v1.0, 2022-05-01

The Context Diagram describes the boundaries of the system with repect to the relationships with the user personas and external systems. It provides an overview of the system, it simplicity make it suitable to present to any kind of public, inluding business stakeholders.

[.helptext]
****
[NOTE]
====
* *Scope:* A single software system.
* *Primary elements:* The software system in scope.
* *Supporting elements:* People (e.g. users, actors, roles, or personas) and software systems (external dependencies) that are directly connected to the software system in scope. Typically these other software systems sit outside the scope or boundary of your own software system, and you don’t have responsibility or ownership of them.
* *Intended audience:* Everybody, both technical and non-technical people, inside and outside of the software development team.
* *Description:* A System Context Diagram is a good starting point for diagramming and documenting a software system, allowing you to step back and see the big picture. Draw a diagram showing your system as a box in the centre, surrounded by its users and the other systems that it interacts with. Detail isn't important here as this is your zoomed out view showing a big picture of the system landscape. The focus should be on people (actors, roles, personas, etc) and software systems rather than technologies, protocols and other low-level details. It's the sort of diagram that you could show to non-technical people.
====
****

*Date:* YYYY-MM-DD

*Status:* Proposed | Accepted | Deprecated

[.helptext]
****
[NOTE]
====
The goal is to communicate the visual representation of your system with the https://c4model.com[C4 Model] convention. 

To produce the schema you have basically two possibilities:

. *draw and export* - Draw and export as an image from https://app.diagrams.net/[diagram.net]. Diagram has C4 shapes by default.
. *model and generate* - Model with https://structurizr.com/dsl[structurizr DSL], the schema will be generated automatically with https://kroki.io/[kroki].
====
****

[structurizr,main,svg,view-key=SystemContext]
----
include::ROOT:partial$/workspace.dsl[]
----
