= Technical Documentation
Marc Guillen <marc@0x01.ooo>
v1.0, 2022-05-01

Welcome to the technical documentation!

Following agile good practices this documentation follows a documentation-as-code principle. It follows a _just enough_ documentation about the team operating model and system architecture, maintained by the product team with the help of the platform owners and architect.

It contains:

* A Team Handbook (HB) materializing the team way of working and operting model.
* A minimalistic Architecture Design Document (ADD) highlighting the most important design drivers, the context, the environment, the decomposition into containers/components and finally the deployment of the system. Basically anything that would give context to the code! This is optional but recommended for all new systems/products.
* A set of Architecture Diagrams showing visually the context, containers, components and deployment following a https://c4model.com[C4 Model]. A picture is worth thousand words!
* The https://github.com/joelparkerhenderson/architecture-decision-record[Architecture Design Records (ADR)] for the system, martializing the team consensus on significant architectural decisions. There are many different, we choose an approach proposed by https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Michael Nygard].

== Contributing

Anyone can contribute to the template!

Feel free to submit PR if you think the documentation needs additions or clarifications. 
Architects and Platform Owners act as maintainers and will review/discuss your submissions. 

== FAQ

=== How to get started?

. Just clone and degit the current repository
. Rename the placeholders to reflect your product
. Remove the _infotext_ and start to document!


[.helptext]
****
[NOTE]
====
The template have info bubble (like this one) to guide you through the application of those artefacts.
Of course your architect is at disposal to walk you through the template!

To get started focus on:

. Define your team api and operating model
. Creating and maintaining your architecture diagrams, along your changes or as part of your Definition-of-Done (DoD)
. Start with a simple System Context Diagram
. Then deep dive with a Container Diagram 
. If you feel the need deep dive even more, go on with a Components Diagram but this a optional
. A Deployment Diagram is almost always helpful, especially in Cloud Environments
. Bootstrapping your architecture decision log and start logging the decisions that impact your architecture
. The ADD is optional for now, but it might be a valuable tool especially when bootstraping a new system. The ADD can also act as a "step back and think" as you rush through delvering functional features.
====
****
